export default [
    { area: '中国', areaEn: 'China', code: '86' },
    { area: '台湾', areaEn: 'Taiwan', code: '886' },
    { area: '香港', areaEn: 'Hong Kong (SAR)', code: '852' },
    { area: '澳门', areaEn: 'Macao', code: '853' },
    { area: '阿富汗', areaEn: 'Afghanistan', code: '93' },
    { area: '阿尔巴尼亚', areaEn: 'Albania', code: '355' },
    { area: '阿尔及利亚', areaEn: 'Algeria', code: '213' },
    { area: '美属萨摩亚', areaEn: 'American Samoa', code: '684' },
    { area: '安道尔', areaEn: 'Andorra', code: '376' },
    { area: '安哥拉', areaEn: 'Angola', code: '244' },
    { area: '安圭拉', areaEn: 'Anguilla', code: '1264' },
    { area: '南极洲', areaEn: 'Antarctica', code: '672' },
    { area: '安提瓜和巴布达', areaEn: 'Antigua and Barbuda', code: '1268' },
    { area: '阿根廷', areaEn: 'Argentina', code: '54' },
    { area: '亚美尼亚', areaEn: 'Armenia', code: '374' },
    { area: '阿鲁巴', areaEn: 'Aruba', code: '297' },
    { area: '澳大利亚', areaEn: 'Australia', code: '61' },
    { area: '奥地利', areaEn: 'Austria', code: '43' },
    { area: '阿塞拜疆', areaEn: 'Azerbaijan', code: '994' },
    { area: '巴林', areaEn: 'Bahrain', code: '973' },
    { area: '孟加拉国', areaEn: 'Bangladesh', code: '880' },
    { area: '巴巴多斯', areaEn: 'Barbados', code: '1246' },
    { area: '白俄罗斯', areaEn: 'Belarus', code: '375' },
    { area: '比利时', areaEn: 'Belgium', code: '32' },
    { area: '伯利兹', areaEn: 'Belize', code: '501' },
    { area: '贝宁', areaEn: 'Benin', code: '229' },
    { area: '百慕大', areaEn: 'Bermuda', code: '1441' },
    { area: '不丹', areaEn: 'Bhutan', code: '975' },
    { area: '玻利维亚', areaEn: 'Bolivia', code: '591' },
    { area: '波黑', areaEn: 'Bosnia and Herzegovina', code: '387' },
    { area: '博茨瓦纳', areaEn: 'Botswana', code: '267' },
    { area: '巴西', areaEn: 'Brazil', code: '55' },
    { area: '英属维尔京群岛', areaEn: 'British Virgin Islands', code: '1284' },
    { area: '文莱', areaEn: 'Brunei Darussalam', code: '673' },
    { area: '保加利亚', areaEn: 'Bulgaria', code: '359' },
    { area: '布基纳法索', areaEn: 'Burkina Faso', code: '226' },
    { area: '缅甸', areaEn: 'Burma', code: '95' },
    { area: '布隆迪', areaEn: 'Burundi', code: '257' },
    { area: '柬埔寨', areaEn: 'Cambodia', code: '855' },
    { area: '喀麦隆', areaEn: 'Cameroon', code: '237' },
    { area: '加拿大', areaEn: 'Canada', code: '1' },
    { area: '佛得角', areaEn: 'Cape Verde', code: '238' },
    { area: '开曼群岛', areaEn: 'Cayman Islands', code: '1345' },
    { area: '中非', areaEn: 'Central African Republic', code: '236' },
    { area: '乍得', areaEn: 'Chad', code: '235' },
    { area: '智利', areaEn: 'Chile', code: '56' },
    { area: '圣诞岛', areaEn: 'Christmas Island', code: '61' },
    { area: '科科斯（基林）群岛', areaEn: 'Cocos (Keeling) Islands', code: '61' },
    { area: '哥伦比亚', areaEn: 'Colombia', code: '57' },
    { area: '科摩罗', areaEn: 'Comoros', code: '269' },
    { area: '刚果（金）', areaEn: 'Democratic Republic of the Congo', code: '243' },
    { area: '刚果（布）', areaEn: 'Republic of the Congo', code: '242' },
    { area: '库克群岛', areaEn: 'Cook Islands', code: ' 682' },
    { area: '哥斯达黎加', areaEn: 'Costa Rica', code: '506' },
    { area: '科特迪瓦', areaEn: "Cote d'Ivoire", code: '225' },
    { area: '克罗地亚', areaEn: 'Croatia', code: '385' },
    { area: '古巴', areaEn: 'Cuba', code: '53' },
    { area: '塞浦路斯', areaEn: 'Cyprus', code: '357' },
    { area: '捷克', areaEn: 'Czech Republic', code: '420' },
    { area: '丹麦', areaEn: 'Denmark', code: '45' },
    { area: '吉布提', areaEn: 'Djibouti', code: '253' },
    { area: '多米尼克', areaEn: 'Dominica', code: '1767' },
    { area: '多米尼加', areaEn: 'Dominican Republic', code: '1809' },
    { area: '厄瓜多尔', areaEn: 'Ecuador', code: '593' },
    { area: '埃及', areaEn: 'Egypt', code: '20' },
    { area: '萨尔瓦多', areaEn: 'El Salvador', code: '503' },
    { area: '赤道几内亚', areaEn: 'Equatorial Guinea', code: '240' },
    { area: '厄立特里亚', areaEn: 'Eritrea', code: '291' },
    { area: '爱沙尼亚', areaEn: 'Estonia', code: '372' },
    { area: '埃塞俄比亚', areaEn: 'Ethiopia', code: '251' },
    { area: '福克兰群岛（马尔维纳斯）', areaEn: 'Falkland Islands (Islas Malvinas)', code: '500' },
    { area: '法罗群岛', areaEn: 'Faroe Islands', code: '298' },
    { area: '斐济', areaEn: 'Fiji', code: '679' },
    { area: '芬兰', areaEn: 'Finland', code: '358' },
    { area: '法国', areaEn: 'France', code: '33' },
    { area: '法属圭亚那', areaEn: 'French Guiana', code: '594' },
    { area: '法属波利尼西亚', areaEn: 'French Polynesia', code: '689' },
    { area: '加蓬', areaEn: 'Gabon', code: '241' },
    { area: '格鲁吉亚', areaEn: 'Georgia', code: '995' },
    { area: '德国', areaEn: 'Germany', code: '49' },
    { area: '加纳', areaEn: 'Ghana', code: '233' },
    { area: '直布罗陀', areaEn: 'Gibraltar', code: '350' },
    { area: '希腊', areaEn: 'Greece', code: '30' },
    { area: '格陵兰', areaEn: 'Greenland', code: '299' },
    { area: '格林纳达', areaEn: 'Grenada', code: '1473' },
    { area: '瓜德罗普', areaEn: 'Guadeloupe', code: '590' },
    { area: '关岛', areaEn: 'Guam', code: '1671' },
    { area: '危地马拉', areaEn: 'Guatemala', code: '502' },
    { area: '根西岛', areaEn: 'Guernsey', code: '1481' },
    { area: '几内亚', areaEn: 'Guinea', code: '224' },
    { area: '几内亚比绍', areaEn: 'Guinea-Bissau', code: '245' },
    { area: '圭亚那', areaEn: 'Guyana', code: '592' },
    { area: '海地', areaEn: 'Haiti', code: '509' },
    { area: '梵蒂冈', areaEn: 'Holy See (Vatican City)', code: '379' },
    { area: '洪都拉斯', areaEn: 'Honduras', code: '504' },
    { area: '匈牙利', areaEn: 'Hungary', code: '36' },
    { area: '冰岛', areaEn: 'Iceland', code: '354' },
    { area: '印度', areaEn: 'India', code: '91' },
    { area: '印度尼西亚', areaEn: 'Indonesia', code: '62' },
    { area: '伊朗', areaEn: 'Iran', code: '98' },
    { area: '伊拉克', areaEn: 'Iraq', code: '964' },
    { area: '爱尔兰', areaEn: 'Ireland', code: '353' },
    { area: '以色列', areaEn: 'Israel', code: '972' },
    { area: '意大利', areaEn: 'Italy', code: '39' },
    { area: '牙买加', areaEn: 'Jamaica', code: '1876' },
    { area: '日本', areaEn: 'Japan', code: '81' },
    { area: '约旦', areaEn: 'Jordan', code: '962' },
    { area: '哈萨克斯坦', areaEn: 'Kazakhstan', code: '73' },
    { area: '肯尼亚', areaEn: 'Kenya', code: '254' },
    { area: '基里巴斯', areaEn: 'Kiribati', code: '686' },
    { area: '朝鲜', areaEn: 'North Korea', code: '850' },
    { area: '韩国', areaEn: 'South Korea', code: '82' },
    { area: '科威特', areaEn: 'Kuwait', code: '965' },
    { area: '吉尔吉斯斯坦', areaEn: 'Kyrgyzstan', code: '996' },
    { area: '老挝', areaEn: 'Laos', code: '856' },
    { area: '拉脱维亚', areaEn: 'Latvia', code: '371' },
    { area: '黎巴嫩', areaEn: 'Lebanon', code: '961' },
    { area: '莱索托', areaEn: 'Lesotho', code: '266' },
    { area: '利比里亚', areaEn: 'Liberia', code: '231' },
    { area: '利比亚', areaEn: 'Libya', code: '218' },
    { area: '列支敦士登', areaEn: 'Liechtenstein', code: '423' },
    { area: '立陶宛', areaEn: 'Lithuania', code: '370' },
    { area: '卢森堡', areaEn: 'Luxembourg', code: '352' },
    { area: '前南马其顿', areaEn: 'The Former Yugoslav Republic of Macedonia', code: '389' },
    { area: '马达加斯加', areaEn: 'Madagascar', code: '261' },
    { area: '马拉维', areaEn: 'Malawi', code: '265' },
    { area: '马来西亚', areaEn: 'Malaysia', code: '60' },
    { area: '马尔代夫', areaEn: 'Maldives', code: '960' },
    { area: '马里', areaEn: 'Mali', code: '223' },
    { area: '马耳他', areaEn: 'Malta', code: '356' },
    { area: '马绍尔群岛', areaEn: 'Marshall Islands', code: '692' },
    { area: '马提尼克', areaEn: 'Martinique', code: '596' },
    { area: '毛里塔尼亚', areaEn: 'Mauritania', code: '222' },
    { area: '毛里求斯', areaEn: 'Mauritius', code: '230' },
    { area: '马约特', areaEn: 'Mayotte', code: '269' },
    { area: '墨西哥', areaEn: 'Mexico', code: '52' },
    { area: '密克罗尼西亚', areaEn: 'Federated States of Micronesia', code: '691' },
    { area: '摩尔多瓦', areaEn: 'Moldova', code: '373' },
    { area: '摩纳哥', areaEn: 'Monaco', code: '377' },
    { area: '蒙古', areaEn: 'Mongolia', code: '976' },
    { area: '蒙特塞拉特', areaEn: 'Montserrat', code: '1664' },
    { area: '摩洛哥', areaEn: 'Morocco', code: '212' },
    { area: '莫桑比克', areaEn: 'Mozambique', code: '258' },
    { area: '纳米尼亚', areaEn: 'Namibia', code: '264' },
    { area: '瑙鲁', areaEn: 'Nauru', code: '674' },
    { area: '尼泊尔', areaEn: 'Nepal', code: '977' },
    { area: '荷兰', areaEn: 'Netherlands', code: '31' },
    { area: '荷属安的列斯', areaEn: 'Netherlands Antilles', code: '599' },
    { area: '新喀里多尼亚', areaEn: 'New Caledonia', code: '687' },
    { area: '新西兰', areaEn: 'New Zealand', code: '64' },
    { area: '尼加拉瓜', areaEn: 'Nicaragua', code: '505' },
    { area: '尼日尔', areaEn: 'Niger', code: '227' },
    { area: '尼日利亚', areaEn: 'Nigeria', code: '234' },
    { area: '纽埃', areaEn: 'Niue', code: '683' },
    { area: '诺福克岛', areaEn: 'Norfolk Island', code: '6723' },
    { area: '北马里亚纳', areaEn: 'Northern Mariana Islands', code: '1' },
    { area: '挪威', areaEn: 'Norway', code: '47' },
    { area: '阿曼', areaEn: 'Oman', code: '968' },
    { area: '巴基斯坦', areaEn: 'Pakistan', code: '92' },
    { area: '帕劳', areaEn: 'Palau', code: '680' },
    { area: '巴拿马', areaEn: 'Panama', code: '507' },
    { area: '巴布亚新几内亚', areaEn: 'Papua New Guinea', code: '675' },
    { area: '巴拉圭', areaEn: 'Paraguay', code: '595' },
    { area: '秘鲁', areaEn: 'Peru', code: '51' },
    { area: '菲律宾', areaEn: 'Philippines', code: '63' },
    { area: '波兰', areaEn: 'Poland', code: '48' },
    { area: '葡萄牙', areaEn: 'Portugal', code: '351' },
    { area: '波多黎各', areaEn: 'Puerto Rico', code: '1809' },
    { area: '卡塔尔', areaEn: 'Qatar', code: '974' },
    { area: '留尼汪', areaEn: 'Reunion', code: '262' },
    { area: '罗马尼亚', areaEn: 'Romania', code: '40' },
    { area: '俄罗斯', areaEn: 'Russia', code: '7' },
    { area: '卢旺达', areaEn: 'Rwanda', code: '250' },
    { area: '圣赫勒拿', areaEn: 'Saint Helena', code: '290' },
    { area: '圣基茨和尼维斯', areaEn: 'Saint Kitts and Nevis', code: '1869' },
    { area: '圣卢西亚', areaEn: 'Saint Lucia', code: '1758' },
    { area: '圣皮埃尔和密克隆', areaEn: 'Saint Pierre and Miquelon', code: '508' },
    { area: '圣文森特和格林纳丁斯', areaEn: 'Saint Vincent and the Grenadines', code: '1784' },
    { area: '萨摩亚', areaEn: 'Samoa', code: '685' },
    { area: '圣马力诺', areaEn: 'San Marino', code: '378' },
    { area: '圣多美和普林西比', areaEn: 'Sao Tome and Principe', code: '239' },
    { area: '沙特阿拉伯', areaEn: 'Saudi Arabia', code: '966' },
    { area: '塞内加尔', areaEn: 'Senegal', code: '221' },
    { area: '塞尔维亚和黑山', areaEn: 'Serbia and Montenegro', code: '381' },
    { area: '塞舌尔', areaEn: 'Seychelles', code: '248' },
    { area: '塞拉利', areaEn: 'Sierra Leone', code: '232' },
    { area: '新加坡', areaEn: 'Singapore', code: '65' },
    { area: '斯洛伐克', areaEn: 'Slovakia', code: '421' },
    { area: '斯洛文尼亚', areaEn: 'Slovenia', code: '386' },
    { area: '所罗门群岛', areaEn: 'Solomon Islands', code: '677' },
    { area: '索马里', areaEn: 'Somalia', code: '252' },
    { area: '南非', areaEn: 'South Africa', code: '27' },
    { area: '西班牙', areaEn: 'Spain', code: '34' },
    { area: '斯里兰卡', areaEn: 'Sri Lanka', code: '94' },
    { area: '苏丹', areaEn: 'Sudan', code: '249' },
    { area: '苏里南', areaEn: 'Suriname', code: '597' },
    { area: '斯瓦尔巴岛和扬马延岛', areaEn: 'Svalbard', code: '47' },
    { area: '斯威士兰', areaEn: 'Swaziland', code: '268' },
    { area: '瑞典', areaEn: 'Sweden', code: '46' },
    { area: '瑞士', areaEn: 'Switzerland', code: '41' },
    { area: '叙利亚', areaEn: 'Syria', code: '963' },
    { area: '塔吉克斯坦', areaEn: 'Tajikistan', code: '992' },
    { area: '坦桑尼亚', areaEn: 'Tanzania', code: '255' },
    { area: '泰国', areaEn: 'Thailand', code: '66' },
    { area: '巴哈马', areaEn: 'The Bahamas', code: '1242' },
    { area: '冈比亚', areaEn: 'The Gambia', code: '220' },
    { area: '多哥', areaEn: 'Togo', code: '228' },
    { area: '托克劳', areaEn: 'Tokelau', code: '690' },
    { area: '汤加', areaEn: 'Tonga', code: '676' },
    { area: '特立尼达和多巴哥', areaEn: 'Trinidad and Tobago', code: '1868' },
    { area: '突尼斯', areaEn: 'Tunisia', code: '216' },
    { area: '土耳其', areaEn: 'Turkey', code: '90' },
    { area: '土库曼斯坦', areaEn: 'Turkmenistan', code: '993' },
    { area: '特克斯和凯科斯群岛', areaEn: 'Turks and Caicos Islands', code: '1649' },
    { area: '图瓦卢', areaEn: 'Tuvalu', code: '688' },
    { area: '乌干达', areaEn: 'Uganda', code: '256' },
    { area: '乌克兰', areaEn: 'Ukraine', code: '380' },
    { area: '阿拉伯联合酋长国', areaEn: 'United Arab Emirates', code: '971' },
    { area: '英国', areaEn: 'United Kingdom', code: '44' },
    { area: '美国', areaEn: 'United States', code: '1' },
    { area: '乌拉圭', areaEn: 'Uruguay', code: '598' },
    { area: '乌兹别克斯坦', areaEn: 'Uzbekistan', code: '998' },
    { area: '瓦努阿图', areaEn: 'Vanuatu', code: '678' },
    { area: '委内瑞拉', areaEn: 'Venezuela', code: '58' },
    { area: '越南', areaEn: 'Vietnam', code: '84' },
    { area: '美属维尔京群岛', areaEn: 'Virgin Islands', code: '1340' },
    { area: '瓦利斯和富图纳', areaEn: 'Wallis and Futuna', code: '681' },
    { area: '也门', areaEn: 'Yemen', code: '967' },
    { area: '赞比亚', areaEn: 'Zambia', code: '260' },
    { area: '津巴布韦', areaEn: 'Zimbabwe', code: '263' },
]
